### ISSUE TITLE
项目结构的一些疑问

### ISSUE THREAD

**Issue by fkajerry** [draJiang/Heptabase-Blog#2]
在阅读项目的代码，发现几个疑问：

1. 为什么 GitHub 里会将 [node_modules](https://github.com/draJiang/Heptabase-Blog/tree/main/node_modules) 目录上传呢？
2. 为什么不增加 代码的 Lint 呢？

**Comment by draJiang** [comment]
抱歉刚看到消息，第一个问题应该已经修复了，我是业余学习的编程所以还有很多东西不懂，多谢你指出问题。
