### ISSUE TITLE
How to update data.json?

### ISSUE THREAD

**Issue by Hz188** [draJiang/Heptabase-Blog#6]
Hi Mr Jiang,
 
follow the README.md, I change the whiteboard id in config.js and deploy it in vercel, but click into the web page, its yours blog content, not updated with mine.

**Comment by draJiang** [comment]
Hello, sorry I haven't had a chance to update the instructions yet.
You need to modify the **action file** in the GitHub action, modify: `https://api.dabing.one?whiteboard_id=your_whiteboard_id'

and run it

**Comment by Hz188** [comment]
Thanks, It's ok now!
